const state={calendar:[],shopping:[],routines:[]};
const tools={
 addShopping(item){if(!state.shopping.includes(item))state.shopping.push(item);return{tool:'add_to_shopping_list',result:`Added ${item}`}},
 schedule(title,time){state.calendar.push({title,time});return{tool:'schedule_calendar_event',result:`Scheduled ${title} at ${time}`}},
 getCalendar(){return{tool:'get_calendar',result:JSON.stringify(state.calendar)}},
 addRoutine(name){state.routines.push(name);return{tool:'create_home_routine',result:`Created ${name}`}},
 getShopping(){return{tool:'get_shopping_list',result:JSON.stringify(state.shopping)}}
};
function agent(request){const q=request.toLowerCase(),calls=[];if(q.includes('movie night')){calls.push(tools.addShopping('Popcorn'),tools.addShopping('Sparkling water'),tools.schedule('Movie night','20:00'));return{answer:'Done. Movie night is prepared for 20:00. I added the snacks and scheduled the event.',calls};}if(q.includes('calendar')||q.includes("what's on")){calls.push(tools.getCalendar());return{answer:state.calendar.length?`Your calendar has ${state.calendar.length} event(s): ${state.calendar.map(x=>x.time+' — '+x.title).join('; ')}.`:'Your calendar is empty.',calls};}if(q.includes('shopping')||q.includes('add ')){let item=q.includes('coffee')?'Coffee':q.includes('popcorn')?'Popcorn':'Milk';calls.push(tools.addShopping(item));return{answer:`Done. ${item} is on your shopping list.`,calls};}if(q.includes('routine')){calls.push(tools.addRoutine(q.includes('quiet')?'Quiet evening':'Focus time'));return{answer:'Done. The routine was created.',calls};}return{answer:'I can coordinate calendar, shopping, and routines. Try “Prepare movie night for Friday at 8”.',calls};}
const $=s=>document.querySelector(s),messages=$('#messages');function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function bubble(text,who){const d=document.createElement('div');d.className='msg '+who;d.innerHTML=`<div class="who">${who==='user'?'YOU':'NEXANIX'}</div><div>${esc(text)}</div>`;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;}
function render(calls){$('#trace').className='trace';$('#trace').innerHTML=calls.length?calls.map(c=>`<div class="call"><div class="tool">✓ ${esc(c.tool)}</div><div class="result">${esc(c.result)}</div></div>`).join(''):'<span class="empty">No tool calls</span>';$('#cal').textContent=state.calendar.length?state.calendar.map(x=>`${x.time} — ${x.title}`).join(' · '):'—';$('#shop').textContent=state.shopping.length?state.shopping.join(', '):'—';$('#routine').textContent=state.routines.length?state.routines.join(', '):'—';}
function run(q){if(!q.trim())return;bubble(q,'user');const r=agent(q);const b=document.createElement('div');b.className='msg bot typing';b.textContent='Agent is planning…';messages.appendChild(b);setTimeout(()=>{b.remove();bubble(r.answer,'bot');render(r.calls)},700)}
$('#form').onsubmit=e=>{e.preventDefault();const i=$('#input');run(i.value);i.value=''};document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>run(b.dataset.q));
